# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - app-tst-uks-postcodes-001

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy-tst:
    uses: ./.github/workflows/_deploy.yml
    with:
      app-name: 'app-tst-uks-postcodes-001'
      environment: 'test'
    secrets:
      publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_71F2F7CB49674FAF9E5C7AD80016E9FB }}
